Repository octagram-kr/pollet-frontend, pull requests merged in 2025-09, with the labels that each got.

#21 [FEAT] 라우팅 구조 수정 및 공용 레이아웃 적용 범위 수정
  src/app/(site)/layout.tsx
  src/app/(surveys)/layout.tsx
  src/app/components/ad-section.tsx
  src/app/components/answer-section.tsx
  src/app/components/best-reward-products-section.tsx
  src/app/components/countdown-timer.tsx
  src/app/components/custom-survey-section.tsx
  src/app/components/duration.tsx
  src/app/components/newest-survey-section.tsx
  src/app/components/product-card.tsx
  src/app/components/progress-section.tsx
  src/app/components/question-list.tsx
  src/app/components/reward-info.tsx
  src/app/components/section-header.tsx
  src/app/components/status-section.tsx
  src/app/components/survey-card.tsx
  src/app/components/survey-preview-section.tsx
  src/app/components/tag-list.tsx
  src/app/components/urgent-carousel-section.tsx
  src/app/components/waiting-survey-section.tsx
  src/app/layout.tsx
  src/app/my-surveys/components/create-survey-card.tsx
  src/app/my-surveys/components/create-survey-tile.tsx
  src/app/my-surveys/components/filter-popover.tsx
  src/app/my-surveys/components/search-input.tsx
  src/app/my-surveys/components/survey-card.tsx
  src/app/my-surveys/components/survey-list.tsx
  src/app/my-surveys/components/survey-tile.tsx
  src/app/my-surveys/components/toolbar-controls.tsx
  src/app/my-surveys/create/components/coming-soon-card.tsx
  src/app/my-surveys/create/components/create-option-section.tsx
  src/app/my-surveys/create/components/description.tsx
  src/app/my-surveys/create/components/direct-card.tsx
  src/app/my-surveys/create/components/section-header.tsx
  src/app/my-surveys/create/components/template-card.tsx
  src/app/my-surveys/create/components/title.tsx
  src/app/my-surveys/create/page.tsx
  src/app/my-surveys/page.tsx
  src/app/my-surveys/register/components/help-tooltip.tsx
  src/app/my-surveys/register/components/payment-button-section.tsx
  src/app/my-surveys/register/components/platform-fee-section.tsx
  src/app/my-surveys/register/components/point-payment-summary.tsx
  src/app/my-surveys/register/components/registration-preview.tsx
  src/app/my-surveys/register/components/reward-detail-section.tsx
  src/app/my-surveys/register/components/reward-type-selector.tsx
  src/app/my-surveys/register/components/survey-to-register.tsx
  src/app/my-surveys/register/components/used-for-reward-section.tsx
  src/app/my-surveys/register/page.tsx
  src/app/page.tsx
  tsconfig.json
Labels: ✨ feature

#24 [FEAT] 로그인 페이지 퍼블리싱
  public/images/kakao_login_large_narrow.png
  src/app/auth/login/components/google-icon.tsx
  src/app/auth/login/components/kakao-icon.tsx
  src/app/auth/login/components/login-box.tsx
  src/app/auth/login/components/login-button.tsx
  src/app/auth/login/components/login-form.tsx
  src/app/auth/login/components/recent-login-method.tsx
  src/app/auth/login/components/sub-message.tsx
  src/app/auth/login/components/welcome-message.tsx
  src/app/auth/login/page.tsx
Labels: ✨ feature

#25 [FEAT] 설문조사 모아보기 페이지 작업
  src/app/components/custom-survey-section.tsx
  src/app/components/newest-survey-section.tsx
  src/app/components/survey-preview-section.tsx
  src/app/components/urgent-carousel-section.tsx
  src/app/components/waiting-survey-section.tsx
  src/app/page.tsx
  src/app/surveys/components/base-modal.tsx
  src/app/surveys/components/counter-section.tsx
  src/app/surveys/components/filter-card.tsx
  src/app/surveys/components/filter-modal-content.tsx
  src/app/surveys/components/filter-section.tsx
  src/app/surveys/components/pagnation.tsx
  src/app/surveys/components/sort-control-section.tsx
  src/app/surveys/components/survey-card.tsx
  src/app/surveys/components/survey-list.tsx
  src/app/surveys/components/survey-tabs.tsx
  src/app/surveys/components/tag-chips-section.tsx
  src/app/surveys/components/tag-list.tsx
  src/app/surveys/components/tag-modal-content.tsx
  src/app/surveys/components/toggle-control.tsx
  src/app/surveys/for-you/components/recommendation-banner-section.tsx
  src/app/surveys/for-you/page.tsx
  src/app/surveys/layout.tsx
  src/app/surveys/page.tsx
  src/app/surveys/urgent/components/countdown-badge.tsx
  src/app/surveys/urgent/components/survey-list-urgent.tsx
  src/app/surveys/urgent/components/target-progress.tsx
  src/app/surveys/urgent/page.tsx
  src/components/icons/index.ts
  src/components/icons/normal/toggle-default-icon.tsx
  src/components/icons/normal/toggle-fill-icon.tsx
  src/components/icons/normal/toggle-lg-off-icon.tsx
  src/components/icons/normal/toggle-lg-on-icon.tsx
  src/components/icons/normal/toggle-sm-off-icon.tsx
  src/components/icons/normal/toggle-sm-on-icon.tsx
  src/components/layout/header.tsx
  src/components/layout/surveys-header.tsx
Labels: ✨ feature

#28 [FEAT] 설문 상세 페이지 작업
  src/app/surveys/[id]/components/content-container.tsx
  src/app/surveys/[id]/components/intro-section/start-survey-button.tsx
  src/app/surveys/[id]/components/intro-section/survey-description.tsx
  src/app/surveys/[id]/components/intro-section/survey-intro-section.tsx
  src/app/surveys/[id]/components/intro-section/survey-title.tsx
  src/app/surveys/[id]/components/intro-section/tag-list.tsx
  src/app/surveys/[id]/components/survey-detail-page.tsx
  src/app/surveys/[id]/components/survey-info-card/duration.tsx
  src/app/surveys/[id]/components/survey-info-card/info-row.tsx
  src/app/surveys/[id]/components/survey-info-card/participant-status.tsx
  src/app/surveys/[id]/components/survey-info-card/reward-info.tsx
  src/app/surveys/[id]/components/survey-info-card/survey-info-card.tsx
  src/app/surveys/[id]/components/survey-info-card/timer.tsx
  src/app/surveys/[id]/page.tsx
  src/app/surveys/components/survey-card.tsx
  src/lib/fetch-survey.ts
  src/types/survey.ts
Labels: ✨ feature

#31 [FIX] 로그인 페이지 빌드 에러 수정
  src/app/auth/login/components/google-icon.tsx
  src/app/auth/login/components/kakao-icon.tsx
  src/app/auth/login/components/login-box.tsx
  src/app/auth/login/components/login-button.tsx
  src/app/auth/login/components/recent-login-method.tsx
Labels: 🔧 fix

#32 [FEAT] 피그마 디자인에 맞춘 로그인 페이지 구현
  PR_TEMPLATE.md
  PR_TEMPLATE_REGISTER_PAGE.md
  src/app/auth/login/components/login-box.tsx
  src/app/auth/login/components/login-button.tsx
  src/app/auth/login/components/login-form.tsx
  src/app/auth/login/components/recent-login-method.tsx
  src/app/auth/login/components/sub-message.tsx
  src/app/auth/login/components/welcome-message.tsx
  src/app/auth/login/layout.tsx
  src/app/auth/login/page.tsx
  src/app/layout.tsx
  src/components/layout/conditional-layout.tsx
Labels: ✨ feature

#50 [FIX] qview 값이 on일 때 답변 선택이나 결과 문구 확인 불가 문제 해결 (#49)
  src/app/surveys/components/survey-card.tsx
Labels: 🔧 fix

#52 [REFACTOR] MOCK 데이터 업데이트
  PR_TEMPLATE_MYPAGE.md
  src/app/components/status-section.tsx
  src/app/components/urgent-carousel-section.tsx
  src/app/my-surveys/create/direct/page.tsx
  src/app/my-surveys/page.tsx
  src/app/my-surveys/register/components/registration-preview.tsx
  src/app/my-surveys/register/components/survey-to-register.tsx
  src/app/my-surveys/register/page.tsx
  src/app/page.tsx
  src/app/surveys/components/survey-card.tsx
  src/app/surveys/components/survey-list.tsx
  src/app/surveys/urgent/components/survey-list-urgent.tsx
Labels: ♻️ refactor

#54 [REFACTOR] 썸네일 이미지 파일 수정
  public/images/thumbnails/AI.png
  public/images/thumbnails/Commerce.png
  public/images/thumbnails/Education.png
  public/images/thumbnails/Entertainment.png
  public/images/thumbnails/Fashion.png
  public/images/thumbnails/Finance.png
  public/images/thumbnails/Food.png
  public/images/thumbnails/Healthcare.png
  public/images/thumbnails/Lifestyle.png
  public/images/thumbnails/Pet.png
  public/images/thumbnails/Travel.png
  public/images/thumbnails/Wellbeing.png
Labels: ♻️ refactor
